---
title: "2023 COLLABORATING FOR BETTER HEALTH: A MULTI-SPECIALTY CONFERENCE"
format: html
---

## Welcome to the 2023 MSC website

This website provides information about the upcoming conference on **Collaborating for Better Health: A Multi-Specialty Conference**. This conference is a joint initiative of **Taipei Municipal Wanfang Hospital** and **Hargeisa Group Hospital**, and aims to promote knowledge exchange and collaboration among health professionals from different specialties and regions.

The conference will be held on **August 13-14, 2023**, from 9:00 AM to 12:00 PM, at the Conference Hall of **Carro Edeg Hotel** in Hargeisa, Somaliland.


TAIPEI MUNICIPAL WANFANG HOSPITAL VERSUS HARGEISA GROUP HOSPITAL

ON AUGUST 13-14, 2023, AT 09:00 AM, SUNDAY-MONDAY

VENUE: CONFERENCE HALL OF CARRO EDEG HOTEL, HARGEISA


1) To register for the conference, please click <a href="https://bit.ly/2ABcDeF">here</a>.


2) Program at a Glance:





<embed 
  type="application/pdf" 
  src="TMM_SLN_tikzposter_2023Aug__portrait_agenda___TMM_Conference_final.pdf"
  width="100%" 
  height="1000px"
  zoom="130%"
>


3) If you are a speaker at the conference, please submit your CV and abstract to the Conference Secretariat by email: texchi2@gmail.com

You can also download the program agenda by clicking on the PDF icon below:


<style>
iframe {
  width: 70%;
}
</style>

  <iframe src="TMM_SLN_tikzposter_2023Aug__portrait_agenda___TMM_Conference_final.pdf" width="50%" height="200px">
  </iframe>
  
  
This website is Updated on <p id="date"></p>
Powered by github
<script>
document.getElementById("date").innerHTML = Date();
</script>

